services:

  # =========================================
  # DATABASE
  # =========================================

  postgres:
    image: postgres:16-alpine
    container_name: ticketapp-postgres
    environment:
      POSTGRES_DB: ticketapp
      POSTGRES_USER: ${DB_USER:-default_ticketapp_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-default_ticketapp_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketapp-network
    restart: unless-stopped

  # =========================================
  # AUTH SERVER (OAUTH 2.0 / OIDC)
  # =========================================

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: ticketapp-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER:-default_ticketapp_user}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-default_ticketapp_password}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ticketapp-postgres:5432/ticketapp
      KC_DB_USERNAME: ${DB_USER:-default_ticketapp_user}
      KC_DB_PASSWORD: ${DB_PASSWORD:-default_ticketapp_password}
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - ticketapp-network
    depends_on:
      - postgres
    restart: unless-stopped

  # =========================================
  # MAIL SERVER (TEST)
  # =========================================

  mailpit:
    image: axllent/mailpit:v1.15.0
    container_name: ticketapp-mailpit
    environment:
      MP_MAX_MESSAGES: 500
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - ticketapp-network
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: ticketapp-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-default_ticketapp_accesskey}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-default_ticketapp_secretkey}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - ticketapp-network
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

networks:
  ticketapp-network:
    driver: bridge