server:
  port: 8080

spring:
  application:
    name: ticketapp-api

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketapp
    username: ${DB_USER:default_ticketapp_user}
    password: ${DB_PASSWORD:default_ticketapp_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ticketapp

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  minio:
    url: http://localhost:9000
    access-key: ${MINIO_ACCESS_KEY:default_ticketapp_accesskey}
    secret-key: ${MINIO_SECRET_KEY:default_ticketapp_secretkey}
    bucket-name: ticket-attachments
  identity:
    keycloak:
      server-url: ${KC_SERVER_URL:http://localhost:8081}
      realm: ${KC_REALM:ticketapp}
      client-id: ${KC_CLIENT_ID:ticketapp-client}
      client-secret: ${KC_CLIENT_SECRET:default_secret}