name: ci.yml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission for Maven wrapper
        run: chmod +x mvnw

      - name: Build and Test with Maven
        env:
          MAVEN_OPTS: "-Xmx1024m -XX:MaxMetaspaceSize=512m"
        run: ./mvnw clean verify -B -ntp

      - name: Build OCI Docker Image
        run: ./mvnw spring-boot:build-image -DskipTests -B -ntp